main: bixgamer707.morehealth.MoreHealth
version: 1.0.1
author: bixgamer707
api-version: 1.13
name: MoreHealth

commands:
  morehealth:
    description: MoreHealth's main command.
    aliases: [mh,mht]
  hearts:
    description: Open the gui to get more hearts.